# ========== Etapa 1: build ==========
FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn -q dependency:go-offline
COPY src ./src
RUN mvn -q clean package -DskipTests

# ========== Etapa 2: runtime ==========
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8801
ENTRYPOINT ["java","-jar","/app/app.jar","--server.port=8801"]